### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_exit to work when running from docker on Ubuntu

### ISSUE THREAD

**Issue by witoldlitwin** [backblaze-b2-samples/b2-zip-files#1]
Hi! I'm trying to run the app using the `docker run -p 80:8000 --env-file .env ghcr.io/backblaze-b2-samples/b2-zip-files:latest` command on a newly-created VPS in Oracle Cloud running Ubuntu. I installed docker on it by following the official docker documentation (and tested it with the hello-world container).
The .env file I created contains all the required values and I think they are correct.

The app throws this error:
```
ERROR:app.py:Cannot access bucket: 'test-bucket'
[2024-11-20 13:04:29 +0000] [7] [INFO] Worker exiting (pid: 7)
libgcc_s.so.1 must be installed for pthread_exit to work
```

My Python version is 3.12.3.
I tried installing GCC in Ubuntu but it didn't help.

I'm new to docker and running stuff through SSH so I might be missing something from the configuration. Can you give some tips?

**Comment by metadaddy** [comment]
Hi @witoldlitwin - it looks like there's a couple of things going on here.

The first is that the app can't see your bucket. It's not clear from that output where the exact issue is, but you can add the following line to `.env` to get an idea:

```
S3FS_LOGGING_LEVEL=DEBUG
```

Note that if it shows an `InvalidAccessKeyId` error, there are two possible causes:

- Your access key (`AWS_ACCESS_KEY_ID`) is not valid
- Your endpoint URL (`AWS_ENDPOINT_URL`) is not correct, so you've got the right key, but you're sending it to the wrong B2 region.

You can login to Backblaze and check the endpoint for your bucket there. In this example, mine is `s3.us-west-004.backblazeb2.com`. Note that `AWS_ENDPOINT_URL` **must** be a URL, like `https://s3.us-west-004.backblazeb2.com`, rather than just the bare domain name. 

<img width="870" alt="image" src="https://github.com/user-attachments/assets/8f60c267-3b61-4eee-9fe5-86f41456d941">

The `libgcc_s.so.1` error occurs as the app is shutting down, so I don't think it is causing the failure to access the bucket. I don't see it when I run the Docker container, but I just added that library and built a new Docker image, so you shouldn't get it any more.

You can update your image with:

```
docker pull ghcr.io/backblaze-b2-samples/b2-zip-files:latest
```

You should see it pulling new image layers from `backblaze-b2-samples/b2-zip-files`.

**Comment by metadaddy** [comment]
I just added a [Troubleshooting](https://github.com/backblaze-b2-samples/b2-zip-files?tab=readme-ov-file#troubleshooting) section to the README with some of the specific errors you might see.

**Comment by witoldlitwin** [comment]
Thank you for the code update and all the tips. I think the issue lies in an incorrect Docker configuration on my end. A simple test script I wrote fails to connect when run inside Docker, but connects fine when executed outside. I'll keep digging.
